name = "pricecrawler"
main = "src/index.js"
compatibility_date = "2026-09-24"

[triggers]
crons = ["*/3 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "pricecrawler-db"
database_id = "6669a5c1-6551-4f8f-9e31-83983a7bd88a"
