"use client";
import {useMemo,useState} from "react";
import {ShieldCheck,Wifi,LockKeyhole,FileText,RefreshCw,AlertTriangle,CheckCircle2} from "lucide-react";

type Mode="WPA3"|"WPA2"|"WPA/WPA2"|"Open";
function passwordScore(p:string){let s=0;if(p.length>=12)s+=30;else if(p.length>=8)s+=20;else s+=5;if(/[a-z]/.test(p))s+=10;if(/[A-Z]/.test(p))s+=10;if(/\d/.test(p))s+=15;if(/[^A-Za-z0-9]/.test(p))s+=15;if(p.length>=16)s+=20;return Math.min(100,s)}
export default function Home(){
const [ssid,setSsid]=useState("");const [mode,setMode]=useState<Mode>("WPA3");const [password,setPassword]=useState("");const [wps,setWps]=useState(false);const [guest,setGuest]=useState(true);const [updated,setUpdated]=useState(true);const [ran,setRan]=useState(false);
const pscore=passwordScore(password);
const score=useMemo(()=>{let n=0;if(mode==="WPA3")n+=40;else if(mode==="WPA2")n+=32;else if(mode==="WPA/WPA2")n+=20;if(pscore>=70)n+=30;else if(pscore>=45)n+=20;else n+=8;if(!wps)n+=15;if(guest)n+=8;if(updated)n+=7;return Math.min(100,n)},[mode,pscore,wps,guest,updated]);
const level=score>=85?"Strong":score>=65?"Good":score>=45?"Needs attention":"At risk";
function report(){const lines=["WIFI SECURITY AUDIT","Network: "+(ssid||"Unnamed test network"),"Encryption: "+mode,"Password strength: "+pscore+"/100","WPS enabled: "+(wps?"Yes":"No"),"Guest network: "+(guest?"Enabled":"Disabled"),"Firmware current: "+(updated?"Yes":"Unknown"),"Overall score: "+score+"/100 ("+level+")","","This report is for an authorized security review. It does not attempt to access, crack, capture, or bypass any wireless network."];navigator.clipboard?.writeText(lines.join("\n"));setRan(true)}
return <main className="wrap">
<nav className="nav"><div className="brand"><div className="brandIcon"><ShieldCheck size={21}/></div>WiFi Security Auditor</div><div className="badge">AUTHORIZED TESTING ONLY</div></nav>
<section className="hero"><div className="panel"><div className="eyebrow">Wireless security posture</div><h1>Audit your Wi‑Fi before attackers do.</h1><p>Check encryption, password hygiene and common router security settings from a clean browser dashboard. Designed for networks you own or are explicitly authorized to test.</p><div className="notice"><AlertTriangle size={18}/><span>This tool is intentionally defensive: it does not crack passwords, deauthenticate clients, capture handshakes, attack WPS, or bypass Wi‑Fi access controls.</span></div></div>
<div className="panel score" style={{"--score":score+"%"} as React.CSSProperties}><div className="ring"><div className="scoreText"><strong>{score}</strong><span>SECURITY SCORE</span></div></div></div></section>
<section className="grid"><div className="card"><Wifi size={20}/><h3>Encryption audit</h3><div className="muted">Review WPA3/WPA2 configuration and identify weak or open encryption choices.</div></div><div className="card"><LockKeyhole size={20}/><h3>Password hygiene</h3><div className="muted">Evaluate a test password locally for length and character diversity.</div></div><div className="card"><FileText size={20}/><h3>Audit report</h3><div className="muted">Generate a concise, shareable report from the settings you entered.</div></div></section>
<section className="panel section"><h2>Run an authorized audit</h2><div className="controls"><div className="field"><label>Network name / SSID</label><input className="input" value={ssid} onChange={e=>setSsid(e.target.value)} placeholder="My Home WiFi"/></div><div className="field"><label>Encryption</label><select className="select" value={mode} onChange={e=>setMode(e.target.value as Mode)}><option>WPA3</option><option>WPA2</option><option>WPA/WPA2</option><option>Open</option></select></div><div className="field"><label>Test password (evaluated locally)</label><input className="input" type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter the password you are authorized to test"/><div className="muted" style={{marginTop:8}}>Strength: {pscore}/100</div></div><div className="field"><label>Password strength</label><input className="range" type="range" min="0" max="100" value={pscore} readOnly/></div></div>
<div className="section"><div className="checkrow"><span>WPS enabled</span><button className={"status "+(wps?"warn":"good")} onClick={()=>setWps(!wps)}>{wps?"Enabled":"Disabled"}</button></div><div className="checkrow"><span>Guest network isolated</span><button className={"status "+(guest?"good":"warn")} onClick={()=>setGuest(!guest)}>{guest?"Enabled":"Disabled"}</button></div><div className="checkrow"><span>Router firmware current</span><button className={"status "+(updated?"good":"warn")} onClick={()=>setUpdated(!updated)}>{updated?"Yes":"Unknown"}</button></div></div>
<div className="actions"><button className="button" onClick={()=>setRan(true)}><ShieldCheck size={16}/> Run audit</button><button className="button secondary" onClick={()=>{setSsid("");setMode("WPA3");setPassword("");setWps(false);setGuest(true);setUpdated(true);setRan(false)}}><RefreshCw size={16}/> Reset</button><button className="button secondary" onClick={report}><FileText size={16}/> Copy report</button></div>
{ran&&<div className="section"><div className="checkrow"><span><CheckCircle2 size={17}/> Audit complete — {level}</span><span className={"status "+(score>=65?"good":score>=45?"warn":"bad")}>{score}/100</span></div><div className="report">Authorized Wi‑Fi Security Audit{"\n\n"}Network: {ssid||"Unnamed test network"}{"\n"}Encryption: {mode}{"\n"}Password strength: {pscore}/100{"\n"}WPS: {wps?"Enabled — review recommended":"Disabled"}{"\n"}Guest network: {guest?"Enabled":"Disabled"}{"\n"}Firmware: {updated?"Current":"Review update status"}{"\n"}Overall: {score}/100 — {level}{"\n\n"}Next steps: prefer WPA3 where supported, use a long unique passphrase, disable WPS when practical, keep router firmware current, and isolate guest devices.</div></div>}</section>
<div className="footer">For networks you own or have explicit permission to assess. Browser-only posture audit; no wireless interface access or attack functionality.</div></main>
}